local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   width: 8.0
   height: 8.0
   resolution: 0.01
   transform_tolerance: 2.0
